### ISSUE TITLE
No default engine was specified and no extension was provided.

### ISSUE THREAD

**Issue by picheli20** [lykmapipo/generator-mvp#32]
When I just create a new application using "yo". And create a api as : `yo mvp:api user name:String email:String password:String`. I receive the following error when I try to make a "get".

Error: No default engine was specified and no extension was provided.
    at new View (/home/fabio/dev/nodejs-simple-api/node_modules/express/lib/view.js:62:11)
    at EventEmitter.render (/home/fabio/dev/nodejs-simple-api/node_modules/express/lib/application.js:569:12)
    at ServerResponse.render (/home/fabio/dev/nodejs-simple-api/node_modules/express/lib/response.js:961:7)
    at html (/home/fabio/dev/nodejs-simple-api/node_modules/express-respond/lib/negotiate.js:26:36)

**Comment by lykmapipo** [comment]
@picheli20 

Am on it. Soon I will publish a fix

**Comment by lykmapipo** [comment]
@picheli20 

Try v1.5.2
